spring:
  jpa:
    database: POSTGRESQL
  profiles: heroku
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
apiRequest:
  url: https://api.exchangerate.host/latest?base=

cron:
  expression: '0 0 */12 * * *'

currencies: PLN,EUR,USD,GBP
---
spring:
  jpa:
    database: POSTGRESQL
  profiles: local
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mati
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

apiRequest:
  url: https://api.exchangerate.host/latest?base=

cron:
  expression: '0 */1 * * * *'

currencies: PLN,EUR,USD,GBP

