spring:
  jpa:
    database: POSTGRESQL

  datasource:
    platform: postgres
    url:
      jdbc:postgresql://localhost:5432/postgres
    username:
      postgres
    password:
      mati

    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8081

apiRequest:
  url: https://api.exchangerate.host/latest?base=PLN

currencies:
  - PLN
  - EUR
  - USD
  - GBP
